env:
  global:
      - REPO_DIR=Pillow
      - BUILD_COMMIT=HEAD
      - PLAT=aarch64
      - DOCKER_TEST_IMAGE=multibuild/focal_{PLAT}
      - TEST_DEPENDS="pytest pytest-timeout"

language: python
# Default Python version is usually 3.6
python: "3.10"
dist: focal
services: docker

jobs:
  include:
    - name: "3.7 Focal aarch64"
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.7
    - name: "3.8 Focal aarch64"
      os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.8
    - name: "3.9 Focal aarch64"
      os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.9
    - name: "3.10 Focal aarch64"
      os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.10

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code
    - build_wheel
    - ls -l "${TRAVIS_BUILD_DIR}/${WHEEL_SDIR}/"

script:
    - install_run

# Upload wheels to GitHub Releases
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/${WHEEL_SDIR}/*.whl"
  on:
    repo: python-pillow/pillow-wheels
  skip_cleanup: true
