language:
  - objective-c

env:
  global:
    - PILLOW_COMMIT=latest-tag
    - REPO_DIR=Pillow
  matrix:
    - VERSION=2.7.10
    - VERSION=3.3.5
    - VERSION=3.4.3
    - VERSION=3.5.0
# Disabled due to pip install issue
#    - VERSION=3.2.5

install:
    - source run_install.sh
    - get_python_environment macpython $VERSION venv
    # Update to latest wheel package for Python 3.5
    - pip install -U wheel
    - pip install delocate
    - if [ -n "$PILLOW_COMMIT" ]; then
        checkout_commit $REPO_DIR $PILLOW_COMMIT;
      fi
    - cd $REPO_DIR
    - python setup.py bdist_wheel
    - delocate-wheel dist/*.whl
    - rename_wheels dist/*.whl
    - pip install dist/*.whl
    - cd ..

script:
    - cd $REPO_DIR
    - python selftest.py --installed
    - pip install nose
    - export NOSE_PROCESS_TIMEOUT=600
    - export NOSE_PROCESSES=0
    - if [ -f test-installed.py ]; then
      python test-installed.py -s -v Tests/test_*.py ;
      else
      python Tests/run.py --installed ;
      fi
    - cd ..

before_deploy:
  - cd $REPO_DIR/dist

deploy:
  provider: cloudfiles
  username: travis-upload
  api-key:
    secure: MqebEoOm+nNwSKWcINYJ0ct6Z16q4DBB9j/plfTw3Xc4Rr8e/OC66/hLBEga5J7afr4TkIK1849xaB2ce/Gxe2+mRM9qbg4ggz2Ul16lKhl9obFZwcP2ttLEqs//LjBHD9MAz1NMRxhwvb80OKuC2dg02/s9K7CRb2sJmDG4nC0=
  region: ORD
  container: wheels
  skip_cleanup: true
