version: 3.3.pre.{build}
clone_folder: c:\pillow
init:
- ECHO %PYTHON%
environment:
  X64_EXT: -x64
  matrix:
  - PYTHON: C:/Python27-x64
  - PYTHON: C:/Python34
  - PYTHON: C:/Python27
  - PYTHON: C:/Python34-x64
  - PYTHON: C:/Python33
  - PYTHON: C:/Python33-x64
install:
- git clone https://github.com/python-pillow/pillow-depends.git c:\pillow-depends
- xcopy c:\pillow-depends\*.zip c:\pillow\winbuild\
- xcopy c:\pillow-depends\*.tar.gz c:\pillow\winbuild\
- cd c:\pillow\winbuild\
- c:\python34\python.exe c:\pillow\winbuild\build_dep.py
- c:\pillow\winbuild\build_deps.cmd
build_script:
- '%PYTHON%\python.exe c:\pillow\winbuild\build.py'
- cd c:\pillow
- dir dist\*.egg
- '%PYTHON%\python.exe selftest.py --installed'
test_script:
- cd c:\pillow
- '%PYTHON%\Scripts\pip.exe install nose'
- '%PYTHON%\python.exe test-installed.py'
matrix:
  fast_finish: true
artifacts:
- path: pillow\dist\*.egg
  name: build
after_test:
  - ps: Get-ChildItem .\dist\*.egg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
deploy:
  provider: S3
  access_key_id: AKIAIRAXC62ZNTVQJMOQ 
  secret_access_key:
    secure: Hwb6klTqtBeMgxAjRoDltiiqpuH8xbwD4UooDzBSiCWXjuFj1lyl4kHgHwTCCGqi
  bucket: pillow-nightly
  folder: win/$(APPVEYOR_BUILD_NUMBER)/
  artifact: /.*egg/

