name: Build macOS wheels

on:
  workflow_call:
    inputs:
      build-commit:
        required: true
        type: string
      artifacts-name:
        required: true
        type: string

env:
  REPO_DIR: Pillow
  TEST_DEPENDS: "pytest pytest-timeout"

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.platform }}
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        python: [ "pypy3.7-7.3.9", "pypy3.8-7.3.9", "3.7", "3.8", "3.9", "3.10", "3.11" ]
        platform: [ "x86_64", "arm64" ]
        exclude:
          - python: "3.7"
            platform: "arm64"
          - python: "pypy3.7-7.3.9"
            platform: "arm64"
          - python: "pypy3.8-7.3.9"
            platform: "arm64"
    env:
      BUILD_COMMIT: ${{ inputs.build-commit }}
      PLAT: ${{ matrix.platform }}
      MB_PYTHON_VERSION: ${{ matrix.python }}
      TRAVIS_OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build Wheel
        run: .github/workflows/build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
          path: wheelhouse/*.whl
      # Uncomment to get SSH access for testing
      # - name: Setup tmate session
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3
