name: Build Linux wheels

on:
  workflow_call:
    inputs:
      artifacts-name:
        required: true
        type: string

env:
  CONFIG_PATH: "wheels/config.sh"
  REPO_DIR: "."
  TEST_DEPENDS: "pytest pytest-timeout"

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.mb-ml-libc }}${{ matrix.mb-ml-ver }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python: [
          "pypy3.9-7.3.13",
          "pypy3.10-7.3.13",
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
        ]
        mb-ml-libc: [ "manylinux" ]
        mb-ml-ver: [ 2014, "_2_28" ]
        include:
          - python: "3.8"
            mb-ml-libc: "musllinux"
            mb-ml-ver: "_1_1"
          - python: "3.9"
            mb-ml-libc: "musllinux"
            mb-ml-ver: "_1_1"
          - python: "3.10"
            mb-ml-libc: "musllinux"
            mb-ml-ver: "_1_1"
          - python: "3.11"
            mb-ml-libc: "musllinux"
            mb-ml-ver: "_1_1"
          - python: "3.12"
            mb-ml-libc: "musllinux"
            mb-ml-ver: "_1_1"
    env:
      MB_PYTHON_VERSION: ${{ matrix.python }}
      MB_ML_LIBC: ${{ matrix.mb-ml-libc }}
      MB_ML_VER: ${{ matrix.mb-ml-ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Build Wheel
        run: .github/workflows/wheels-build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
          path: wheelhouse/*.whl
      # Uncomment to get SSH access for testing
      # - name: Setup tmate session
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3
