name: Wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/wheels-build.yml
    with:
      build-commit: "HEAD"
      artifacts-name: "wheels"

  build-latest:
    if: "!startsWith(github.ref, 'refs/tags/')"
    uses: ./.github/workflows/wheels-build.yml
    with:
      build-commit: "main"
      artifacts-name: "wheels-latest"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Upload Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success:
    needs: [build, build-latest]
    runs-on: ubuntu-latest
    name: Wheels Successful
    steps:
      - name: Success
        run: echo Wheels Successful
