name: Build Linux wheels

on:
  workflow_call:
    inputs:
      build-commit:
        required: true
        type: string
      artifacts-name:
        required: true
        type: string

env:
  REPO_DIR: Pillow
  TEST_DEPENDS: "pytest pytest-timeout"

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.mb-ml-libc }}${{ matrix.mb-ml-ver }} ${{ matrix.platform }}
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        python: [ "pypy3.7-7.3.9", "pypy3.8-7.3.9", "3.7", "3.8", "3.9", "3.10", "3.11" ]
        platform: [ "i686", "x86_64" ]
        mb-ml-libc: [ "manylinux" ]
        mb-ml-ver: [ 2014, "_2_28" ]
        exclude:
          - platform: "i686"
            mb-ml-ver: "_2_28"
        include:
          - python: "3.8"
            platform: "x86_64"
            mb-ml-libc: "musllinux"
            mb-ml-ver: "_1_1"
          - python: "3.9"
            platform: "x86_64"
            mb-ml-libc: "musllinux"
            mb-ml-ver: "_1_1"
          - python: "3.10"
            platform: "x86_64"
            mb-ml-libc: "musllinux"
            mb-ml-ver: "_1_1"
          - python: "3.11"
            platform: "x86_64"
            mb-ml-libc: "musllinux"
            mb-ml-ver: "_1_1"
    env:
      BUILD_COMMIT: ${{ inputs.build-commit }}
      PLAT: ${{ matrix.platform }}
      MB_PYTHON_VERSION: ${{ matrix.python }}
      MB_ML_LIBC: ${{ matrix.mb-ml-libc }}
      MB_ML_VER: ${{ matrix.mb-ml-ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build Wheel
        run: .github/workflows/build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
          path: wheelhouse/*.whl
      # Uncomment to get SSH access for testing
      # - name: Setup tmate session
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3
